#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Generated by rules_openxc7: programs a bitstream with openFPGALoader.
# Arguments after `bazel run <target> --` go to openFPGALoader, after the
# ones below; `-c <cable>` among them overrides the rule's cable.
# OPENXC7_DRY_RUN=1 prints the command instead of running it.
set -euo pipefail

runfiles="${RUNFILES_DIR:-$0.runfiles}"
ofl="$runfiles/@@OFL@@"
bit="$runfiles/@@BIT@@"

cmd=("$ofl" @@ARGS@@ "$@" "$bit")
if [[ "${OPENXC7_DRY_RUN:-}" == "1" ]]; then
  printf '%q ' "${cmd[@]}"
  echo
  exit 0
fi
exec "${cmd[@]}"
