#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Generated by rules_openxc7: the runner of the emulated Vivado toolchain.
#
# rules_vivado prefixes every Vivado command line with its toolchain's
# runner, as in
#
#   <runner> --container=... --envs=... [more --flags] \
#     LD_LIBRARY_PATH="<vivado_path>/lib/lnx64.o" \
#     <vivado_path>/bin/setEnvAndRunCmd.sh vivado -mode batch -source x.tcl p.xpr
#
# This accepts the same flags as rules_vivado's host runner, and runs the
# Vivado emulation of rules_openxc7 in place of vivado. Any other command
# (xsim, hw_server, ...) is refused: it is not emulated.
set -euo pipefail

runfiles="$0.runfiles"
[[ -d "$runfiles" ]] || runfiles="${RUNFILES_DIR:?no runfiles for $0}"
export RUNFILES_DIR="$runfiles"

envs=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --envs=*) IFS=',' read -r -a envs <<< "${1#--envs=}"; shift ;;
    --) shift; break ;;
    --*) shift ;;
    *) break ;;
  esac
done
for kv in "${envs[@]}"; do
  [[ -n "$kv" ]] && export "${kv?}"
done

# Find `.../setEnvAndRunCmd.sh <tool>` and keep what follows it.
tool=""
while [[ $# -gt 0 ]]; do
  if [[ "$1" == */setEnvAndRunCmd.sh ]]; then
    tool="${2:-}"
    shift 2 || shift $#
    break
  fi
  shift
done
if [[ "$tool" != "vivado" ]]; then
  echo "rules_openxc7: '${tool:-<none>}' is not emulated; only vivado -mode batch is" >&2
  exit 1
fi

@@EXPORTS@@

# The emulation and its Python, unpacked outside the working directory (see
# runner.bzl for why they are packed).
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
tar -xf "$runfiles/@@ARCHIVE@@" -C "$work"
PYTHONPATH="$work/src" PYTHONNOUSERSITE=1 "$work/@@INTERPRETER@@" \
  "$work/src/vivado/private/vivado_emulator.py" "$@"
